name             'marcus-workstation'
maintainer       'Marcus Peterson'
maintainer_email 'marcus.g.peterson@gmail.com'
license          'MIT'
description      'Installs/Configures marcus-workstation'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
supports         'mac_os_x'
depends          'homebrew', '>= 1.6.6'
depends          'zip_app'
